### ISSUE TITLE
New SSG Feature: Support --config with Config File

### ISSUE THREAD

**Issue by mnosov622** [ritikbheda/commandline-ssg#18]
Dear Ritik Bheda,

Reaching out to say that I would love to add a new feature to your SSG tool. 

I would love to add support for config file, that will contain all SSG options (input file, output file, style file and language).

**Comment by ritikbheda** [comment]
Hi @mnosov622, sure, I'd love that feature on the project! 
Please proceed to it and let me know if you'd like to know something from my side for doing the same.

**Comment by mnosov622** [comment]
Hi @ritikbheda  !

It seems that this feature is already implemented, let me know how else I can contribute :)
